set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_BUILD_TYPE release)
set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_CMAKE_SYSTEM_VERSION 20.0)
set(VCPKG_OSX_ARCHITECTURES arm64)
set(VCPKG_CMAKE_CONFIGURE_OPTIONS -DCMAKE_SYSROOT=/opt/aarch64-apple-darwin20/aarch64-apple-darwin20/sys-root -DCMAKE_SYSTEM_FRAMEWORK_PATH=/opt/aarch64-apple-darwin20/aarch64-apple-darwin20/sys-root/System/Library/Frameworks)
